development:
  adapter: postgresql
  encoding: unicode
  database: start_up
  pool: 5
  username: start_up
  password: start_up

production:
  adapter: postgresql
  encoding: unicode
  database: start_up
  pool: 5
